# Generated by Django 4.2.16 on 2024-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorychange',
            old_name='quantity_changed',
            new_name='new_quantity',
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='previous_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
