# Generated by Django 4.2.16 on 2024-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_quantity_changed_inventorychange_new_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorychange',
            name='previous_quantity',
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
